coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 2%
      python:
        target: 90%
        threshold: 2%
        flags:
          - python
      julia:
        target: 90%
        threshold: 2%
        flags:
          - julia
      rust:
        target: 90%
        threshold: 2%
        flags:
          - rust
      cpp:
        target: 90%
        threshold: 2%
        flags:
          - cpp
      r:
        target: 90%
        threshold: 2%
        flags:
          - r

flags:
  python:
    paths:
      - python/src/
    carryforward: true
  julia:
    paths:
      - julia/src/
    carryforward: true
  rust:
    paths:
      - rust/src/
    carryforward: true
  cpp:
    paths:
      - cpp/include/
    carryforward: true
  r:
    paths:
      - r/R/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
