#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Arnaldo Mendes Pires Junior
# SPDX-License-Identifier: MIT

set -euo pipefail

COMPOSE_FILE="docker/local-ci/docker-compose.yml"
DEFAULT_TARGETS=(workflow-lint python rust julia cpp r sonarqube)
CONTINUE_ON_ERROR=false
AUTO_CLEANUP_BUILDS=false
ENV_FILE=".env"
BUILD_ROOT="cpp/build"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/local-ci/run.sh [target ...] [--continue-on-error] [--cleanup-builds]

Targets:
  workflow-lint  Validate GitHub Actions workflows with actionlint
  python         Run CI-equivalent Python jobs
  rust           Run CI-equivalent Rust jobs
  julia          Run CI-equivalent Julia jobs
  cpp            Run CI-equivalent C++ jobs
  r              Run CI-equivalent R jobs
  sonarqube      Run local SonarQube scan (requires SONAR_TOKEN and SONAR_HOST_URL)
                 Automatically runs preflight targets: cpp, julia, r
  all            Run all targets above (default)

Examples:
  bash scripts/local-ci/run.sh
  bash scripts/local-ci/run.sh workflow-lint python
  bash scripts/local-ci/run.sh cpp --cleanup-builds
  RUN_MUTATION=true bash scripts/local-ci/run.sh python
EOF
}

cleanup_build_artifacts() {
  if [ "$AUTO_CLEANUP_BUILDS" != true ]; then
    return
  fi

  if [ -d "$BUILD_ROOT" ]; then
    echo "Cleaning local C++ build artifacts from $BUILD_ROOT"
    rm -rf "$BUILD_ROOT"
  fi
}

trap cleanup_build_artifacts EXIT

append_target_once() {
  local target="$1"
  local existing
  for existing in "${TARGETS[@]}"; do
    if [ "$existing" = "$target" ]; then
      return
    fi
  done
  TARGETS+=("$target")
}

if [ ! -f "$COMPOSE_FILE" ]; then
  echo "Missing compose file: $COMPOSE_FILE"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker CLI is required."
  exit 1
fi

TARGETS=()
for arg in "$@"; do
  case "$arg" in
    -h|--help)
      usage
      exit 0
      ;;
    --continue-on-error)
      CONTINUE_ON_ERROR=true
      ;;
    --cleanup-builds)
      AUTO_CLEANUP_BUILDS=true
      ;;
    all)
      TARGETS=("${DEFAULT_TARGETS[@]}")
      ;;
    workflow-lint|python|rust|julia|cpp|r|sonarqube)
      TARGETS+=("$arg")
      ;;
    *)
      echo "Unknown target: $arg"
      usage
      exit 2
      ;;
  esac
done

if [ "${#TARGETS[@]}" -eq 0 ]; then
  TARGETS=("${DEFAULT_TARGETS[@]}")
fi

# SonarQube local scan needs artifacts generated by other language jobs:
# - cpp: cpp/build/sonar/compile_commands.json for CFamily analysis
# - julia: julia-lcov.info for Julia coverage import
# - r: validate package/tests before scan
HAS_SONAR=false
for target in "${TARGETS[@]}"; do
  if [ "$target" = "sonarqube" ]; then
    HAS_SONAR=true
    break
  fi
done

if [ "$HAS_SONAR" = true ]; then
  EXPANDED=()
  for target in "${TARGETS[@]}"; do
    if [ "$target" = "sonarqube" ]; then
      for pre in cpp julia r; do
        found=false
        for current in "${EXPANDED[@]}"; do
          if [ "$current" = "$pre" ]; then
            found=true
            break
          fi
        done
        if [ "$found" = false ]; then
          EXPANDED+=("$pre")
        fi
      done
    fi
    found=false
    for current in "${EXPANDED[@]}"; do
      if [ "$current" = "$target" ]; then
        found=true
        break
      fi
    done
    if [ "$found" = false ]; then
      EXPANDED+=("$target")
    fi
  done
  TARGETS=("${EXPANDED[@]}")
fi

FAILED=()
for target in "${TARGETS[@]}"; do
  echo "==== Running target: ${target} ===="
  compose_cmd=(docker compose -f "$COMPOSE_FILE")
  if [ -f "$ENV_FILE" ]; then
    compose_cmd+=(--env-file "$ENV_FILE")
  fi
  run_env=()
  # Keep local sonarqube preflight aligned with CI SonarQube workflow:
  # generate Julia coverage artifacts, but do not enforce formatter gate here.
  if [ "$HAS_SONAR" = true ] && [ "$target" = "julia" ]; then
    run_env+=(LOCAL_CI_JULIA_SKIP_FORMAT=true)
  fi
  if ! env "${run_env[@]}" "${compose_cmd[@]}" run --rm "$target"; then
    FAILED+=("$target")
    if [ "$CONTINUE_ON_ERROR" = false ]; then
      echo "Target failed: $target"
      exit 1
    fi
  fi
done

if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "Failed targets: ${FAILED[*]}"
  exit 1
fi

echo "All selected local CI targets passed."
